-- Store audits: completed physical-count audits + per-line detail and
-- post-audit reconciliation decisions.
--
-- Conventions follow the rest of the schema: character varying primary keys
-- (generated by the application, not the DB), FKs to stores/users, and
-- CURRENT_TIMESTAMP defaults.

-- ============================================================
-- store_audits — one row per completed audit
-- ============================================================
CREATE TABLE IF NOT EXISTS public.store_audits (
  id character varying NOT NULL,
  store_id character varying NOT NULL REFERENCES public.stores(id),
  store_name character varying,
  store_code character varying,
  audited_by character varying REFERENCES public.users(id),
  started_at timestamp without time zone,
  completed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

  -- rolled-up line counts
  verified_lines integer NOT NULL DEFAULT 0,
  short_lines integer NOT NULL DEFAULT 0,
  unscanned_lines integer NOT NULL DEFAULT 0,
  missing_lines integer NOT NULL DEFAULT 0,
  found_lines integer NOT NULL DEFAULT 0,
  over_count_lines integer NOT NULL DEFAULT 0,

  -- rolled-up units / value (selling-price basis)
  scanned_units integer NOT NULL DEFAULT 0,
  system_units integer NOT NULL DEFAULT 0,
  discrepancy_units integer NOT NULL DEFAULT 0,
  discrepancy_value numeric NOT NULL DEFAULT 0,
  shortage_value numeric NOT NULL DEFAULT 0,
  surplus_value numeric NOT NULL DEFAULT 0,
  accuracy_pct integer NOT NULL DEFAULT 0,

  status character varying DEFAULT 'completed',   -- completed | reconciled
  note text,

  -- reconciliation
  reconciled_at timestamp without time zone,
  reconciled_by character varying REFERENCES public.users(id),

  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT store_audits_pkey PRIMARY KEY (id),
  CONSTRAINT store_audits_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT store_audits_audited_by_fkey FOREIGN KEY (audited_by) REFERENCES public.users(id),
  CONSTRAINT store_audits_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES public.users(id)
);

CREATE INDEX IF NOT EXISTS idx_store_audits_store_completed
  ON public.store_audits (store_id, completed_at DESC);

CREATE INDEX IF NOT EXISTS idx_store_audits_status
  ON public.store_audits (status);

-- ============================================================
-- store_audit_items — one row per product line in an audit
-- ============================================================
-- NOTE: product_id is intentionally NOT a foreign key. An audit is a snapshot,
-- and "newly found" / unknown-barcode lines may reference a code that is not a
-- catalog product. name/barcode/price are stored on the row so the report is
-- self-contained regardless.
CREATE TABLE IF NOT EXISTS public.store_audit_items (
  id character varying NOT NULL,
  audit_id character varying NOT NULL REFERENCES public.store_audits(id) ON DELETE CASCADE,
  product_id character varying,
  name character varying,
  barcode character varying,
  system_qty integer NOT NULL DEFAULT 0,
  counted_qty integer NOT NULL DEFAULT 0,
  outcome character varying NOT NULL,   -- verified | short | unscanned | missing | found | over
  price numeric NOT NULL DEFAULT 0,
  line_value numeric NOT NULL DEFAULT 0,

  -- reconciliation decision for this line (null until reconciled)
  resolution_action character varying,  -- sold_offline | lost | damaged | topup_from_owner | ignore
                                        -- | add_to_store | allocate_from_owner | create_order | flag_only
  resolution_qty integer DEFAULT 0,
  resolution_amount numeric,
  resolution_note text,
  resolved boolean DEFAULT false,

  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT store_audit_items_pkey PRIMARY KEY (id),
  CONSTRAINT store_audit_items_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.store_audits(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_store_audit_items_audit
  ON public.store_audit_items (audit_id);

CREATE INDEX IF NOT EXISTS idx_store_audit_items_product
  ON public.store_audit_items (product_id);
